### ISSUE TITLE
*Existing* and *NewTab* don't work as expected

### ISSUE THREAD

**Issue by sirewix** [ptzz/lf.vim#45]
For \*Existing\* the new buffer is opened even if the file is already open.
For \*NewTab\* opens in a new buffer instead of a tab

VIM 9.1 from arch linux repo

**Comment by ptzz** [comment]
I'm not a tab user and these are commands inherited from upstream. But they seem to work as expected for me

- `LfCurrentDirectoryExistingOrNewTab` then selecting a file already open in another tab, switches to that tab
- `LfNewTab` opens a new tab with the selected file, regardless if it exists in another tab or not

PR welcome since I'm not overly motivated to maintain commands I don't use and rather remove them if they don't work properly.

I'm using NVIM v0.9.5 on Mac.

**Comment by sirewix** [comment]
Should've read the readme:
> **Note**: lf.vim should be loaded before vim-floaterm to override vim-floaterm's lf wrapper.

If using vim pack, enforced ordering my be achieved by making a package optional 
```sh
pack/plugins$ mv start/lf.vim opt/
```

and loading in manually in `.vimrc`:
```vimrc
packadd! lf.vim
```

**Comment by sirewix** [comment]
For [some reason](https://stackoverflow.com/questions/67930489/native-vim-plugin-load-order) `packadd!` reverses order of loading, so you'd need

```vimrc
packadd! vim-floaterm
packadd! lf.vim
```

**Comment by ptzz** [comment]
The order issue pops up now and then and is a bit annoying. Don't know if there is a way to enforce it or fail in runtime with a message if order is not right.
