### ISSUE TITLE
Trying to edit a file using 'e' a nested neovim instance

### ISSUE THREAD

**Issue by RonanMacF** [ptzz/lf.vim#6]
Using the keys 'l' or '<right-arrow>' it opens the file fine, however, pressing 'e' opens up a nested neovim instance. 'e' would be the more intuitive way for me to open files.

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
```

**Comment by ptzz** [comment]
I think this is expected behaviour. The way the vim<->lf communication works, lf needs to _open_ the file to exit and pass it back to the original vim process. Pressing “e” means _edit_ in lf, i.e. will just open a process of $EDITOR.

If you mostly use lf inside vim I guess you could remap “e” to open.
